USE [CSUTIL]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DropDBs] @Databases VARCHAR(MAX)
AS

-------------------------------
----DROP MULTIPLE DATABASES----
-------------------------------
DECLARE @XML XML
SET @XML = CAST('<i>' + REPLACE(@Databases, ',', '</i><i>') + '</i>' AS XML)

DECLARE @DB_ALTER_VAR VARCHAR(MAX)
DECLARE @DB_DROP_VAR VARCHAR(MAX)
DECLARE DB_DROP_CURSOR CURSOR FOR
SELECT
'ALTER DATABASE ' + NAME + ' SET SINGLE_USER WITH ROLLBACK IMMEDIATE' AS 'ALTER SCRIPTS',
'DROP DATABASE ' + NAME AS 'DROP SCRIPTS'
FROM SYS.SYSDATABASES
INNER JOIN @XML.nodes('i') x(i) 
        ON  SYS.SYSDATABASES.NAME = x.i.value('.', 'VARCHAR(MAX)')

OPEN DB_DROP_CURSOR
WHILE 1 = 1
BEGIN
    FETCH DB_DROP_CURSOR INTO @DB_ALTER_VAR, @DB_DROP_VAR
    IF @@FETCH_STATUS != 0 BREAK
    --PRINT(@DB_ALTER_VAR + '     ' + @DB_DROP_VAR);
	EXEC (@DB_ALTER_VAR + '     ' + @DB_DROP_VAR)
END
PRINT (@Databases + ' HAVE BEEN DROPPED')
CLOSE DB_DROP_CURSOR;
DEALLOCATE DB_DROP_CURSOR
GO
