USE [CSUTIL]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[PrintActiveDBs]
AS

---------------------------------------------
----GENERATE DATABASE LIST FOR SHAREPOINT----
---------------------------------------------
CREATE TABLE #DB_VERSIONS 
(
DB_NAME VARCHAR(MAX),
DB_VERSION VARCHAR(MAX)
)

DECLARE @DB_VERSIONS_VAR VARCHAR(MAX)
DECLARE DB_VERSIONS_CURSOR CURSOR FOR
SELECT 
'
INSERT INTO #DB_VERSIONS
VALUES (''' + NAME + ''', (SELECT VER_PRODUCT_VERSION FROM ' + NAME + '.COMMON.VISION_VERSION))
'
FROM SYS.DATABASES
WHERE NAME NOT IN ('master','tempdb','model','msdb','ReportServer','ReportServerTempDB','CSUTIL','AssessPro')

OPEN DB_VERSIONS_CURSOR
WHILE 1 = 1
BEGIN
    FETCH DB_VERSIONS_CURSOR INTO @DB_VERSIONS_VAR
    IF @@FETCH_STATUS != 0 BREAK
    --PRINT(@DB_VERSIONS_VAR)
	EXEC (@DB_VERSIONS_VAR)
END
CLOSE DB_VERSIONS_CURSOR;
DEALLOCATE DB_VERSIONS_CURSOR

SELECT 
	REPLACE(SUSER_SNAME(OWNER_SID),'CORP\','') AS 'Owner',
	(NAME + ',') AS 'DB Name', 
	DB_VERSION AS 'DB VERSION',
	FORMAT (CREATE_DATE, 'd') AS 'Create Date'
 FROM MASTER.SYS.DATABASES
 JOIN #DB_VERSIONS ON DB_NAME = NAME
 WHERE NAME NOT IN ('master','tempdb','model','msdb','ReportServer','ReportServerTempDB','CSUTIL')
 ORDER BY 'Owner'

DROP TABLE #DB_VERSIONS;
GO


